# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6cebd9630419c884aba955cada77a019e7158c85eaaaf76feb7539af142173c92efbdb8983708b675d6d3a3f102019608078a9ae84a10d0dd7defd5b1eb36b1

test:
  secret_key_base: 3dcf3633ff8b8ab68694a7996189fb4ee56679d429deb02e4f1c081009a34d202fe6536e27753be4f2c6119704ca5b65270a34c7bf0153f2af2cadf7182707d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
